"""Initial migration

Revision ID: 7e24b47ac758
Revises: bb1187841533
Create Date: 2025-12-10 16:26:37.728532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e24b47ac758'
down_revision: Union[str, Sequence[str], None] = 'bb1187841533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiters_id', sa.Integer(), nullable=False))
        batch_op.drop_column('waiter_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiter_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('waiters_id')

    # ### end Alembic commands ###
