"""Initial migration

Revision ID: dcc28913eec1
Revises: 7e24b47ac758
Create Date: 2025-12-10 16:29:13.613481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc28913eec1'
down_revision: Union[str, Sequence[str], None] = '7e24b47ac758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=False))
        batch_op.drop_column('dish_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
